[versions]
agp = "8.13.0"
ksp = "2.2.20-2.0.4"
kotlin = "2.2.21"
kotlin-serialization = "1.9.0"

dagger-hilt = "2.57.2"
dagger-hilt-compose = "1.3.0"

androidx-splashscreen = "1.0.1"
imageloader-coil = "3.3.0"

coroutines = "1.10.2"
coreKtx = "1.17.0"

appcompat = "1.7.1"
material = "1.13.0"

ui-compose = "2025.10.01"
ui-compose-activity = "1.11.0"
ui-compose-viewmodel = "2.9.4"
ui-compose-fonts = "1.9.4"
ui-navigation = "2.9.5"

network-okhttp = "5.2.1"
network-ktor = "3.3.1"

test-network-mockserver = "5.15.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
agp3 = "8.13.0"
kotlin3 = "2.2.21"
runtime = "1.9.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-spashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splashscreen"}
android-google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }

dependency-injection-dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
dependency-injection-dagger-hilt-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "dagger-hilt-compose" }
dependency-injection-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }

imageloader-coil-bom={module = "io.coil-kt.coil3:coil-bom", version.ref="imageloader-coil"}
imageloader-coil-compose ={module = "io.coil-kt.coil3:coil-compose"}
imageloader-coil={module = "io.coil-kt.coil3:coil"}
imageloader-coil-core={module = "io.coil-kt.coil3:coil-core"}
imageloader-coil-network-core={module = "io.coil-kt.coil3:coil-network-core-android"}
imageloader-coil-gif={module = "io.coil-kt.coil3:coil-gif"}
imageloader-coil-svg={module = "io.coil-kt.coil3:coil-svg"}
imageloader-coil-video={module = "io.coil-kt.coil3:coil-video"}
imageloader-coil-android={module = "io.coil-kt.coil3:coil-core-android"}
imageloader-coil-cache-strategy={module = "io.coil-kt.coil3:coil-network-cache-control"}
imageloader-coil-okhttp={module = "io.coil-kt.coil3:coil-network-okhttp"}

kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

ui-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "ui-compose"}
ui-compose-material3 = { module = "androidx.compose.material3:material3"}
ui-compose-preview = { module = "androidx.compose.ui:ui-tooling-preview"}
ui-compose-tools = { module = "androidx.compose.ui:ui-tooling"}
ui-compose-adaptive = { module = "androidx.compose.material3.adaptive:adaptive"}
ui-compose-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout"}
ui-compose-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation"}
ui-compose-navigation-suit = { module = "androidx.compose.material3:material3-adaptive-navigation-suite"}
ui-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "ui-compose-activity"}
ui-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "ui-compose-viewmodel"}
ui-compose-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "ui-compose-fonts"}

ui-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "ui-navigation"}
ui-navigation-view = { module = "androidx.navigation:navigation-ui", version.ref = "ui-navigation"}
ui-navigation-view-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "ui-navigation"}
ui-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "ui-navigation"}
ui-navigation-feature = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "ui-navigation"}

network-okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "network-okhttp"}
network-okhttp = { module = "com.squareup.okhttp3:okhttp" }
network-okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor" }

network-ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "network-ktor" }
network-ktor-client = { module = "io.ktor:ktor-client-core" }

test-network-mockserver-netty = { module = "org.mock-server:mockserver-netty", version.ref = "test-network-mockserver"}
test-network-mockserver-client = { module = "org.mock-server:mockserver-client-java", version.ref = "test-network-mockserver"}

test-ui-navigation = { module = "androidx.navigation:navigation-testing", version.ref = "ui-navigation"}

#Plugin dependencies
gradle-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
gradle-kotlin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
gradle-android-compose-compiler = { module = "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin",  version.ref = "kotlin"}
gradle-dependency-injection-hitl = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger-hilt"}
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }


[plugins]
android-application = { id = "android-app" }
android-lib = { id = "android-lib" }
android-kotlin-dependencies = { id = "kotlin-dependencies" }
android-ui-compose = { id = "android-ui-compose" }
android-ui-libraries = { id = "android-ui-libraries" }
android-dependency-injection = { id = "android-dependency-injection" }
android-library = { id = "com.android.library", version.ref = "agp3" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin3" }
#android-library = { id = "com.android.library", version.ref = "agp2" }
#kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin2" }
