name: Release Build
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
job: 
  build-release-version
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v5
      - name: Setup java 21 
      - uses: actions/setup-java@v5.1.0
        with:
          java-version: '21'
          distribution: 'oracle'
          architecture: x64
          cache: gradle
      - name: Run tests
      - run: ./gradlew :apps:mobile:app:assembleRelease 
        
      
