name: Lint
run-name: Lint check on ${{ github.ref_name }}

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref_name }}
      - uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.ref_name }}
      - run: ./gradlew lint
