name: Lint
run-name: Lint check on ${{ github.ref_name }}

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5.1.0
        with: 
          distribution: 'temurin'
          java-version: 21
      - uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.ref_name }}
      - run: ./gradlew lint
