name: Lint
run-name: Lint check on

on: [push]

jobs:
  Lint:
    runs-on: ubunto-latest
    steps:
      - run: echo ${{ github.ref_name }}
      - uses: actions/checkout@v6.0.1
        with:
          ref: ${{ github.ref_name }}
